#+- SVN Keywords ----------------------------------------------------+
#|                                                                   |
#| $HeadURL::                                                      $:|
#|     $Rev::                                                      $:|
#|    $Date::                                                      $:|
#|  $Author::                                                      $:|
#|                                                                   |
#+-------------------------------------------------------------------+

__start__:
	doxygen Doxyfile 2> doxy.log
#	less doxy.log

clean:
	rm -fr html doxy.log
